apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app:  {{ .Values.application }}
    tier: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP      
  selector:
    app:  {{ .Values.application }}
    tier: backend
