apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app:  {{ .Values.application }}
    tier: backend    
spec:
  replicas: {{ .Values.replicaCount }}  
  selector:
    matchLabels:
      app:  {{ .Values.application }}
      tier: backend 
  template:
    metadata:     
      labels:
        app:  {{ .Values.application }}
        tier: backend 
    spec:           
      containers:
      - env:
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_NAME
          value: product
        - name: DATABASE_PASSWORD
          value: pr0dr0b0t
        - name: DATABASE_USER
          value: product_robot
        - name: DATABASE_PORT
          value: "5432"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 8080
      restartPolicy: Always
