apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
spec:
  serviceName: "postgres"
  selector:
    matchLabels:
        app: {{ .Values.application }}
        tier: postgres
  template:
    metadata:
      labels:
        app: {{ .Values.application }}
        tier: postgres
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        envFrom:
          - configMapRef:
              name: {{ .Values.configMapRef.name }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: postgredb
        volumeMounts:
        - name: postgredb
          mountPath: /var/lib/postgresql
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
