apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2021-08-27T05:21:12Z"
  name: mytestacc
  namespace: default
  resourceVersion: "1223361"
  uid: f85e3448-b83a-4e39-9ba5-8edfa78d137d
secrets:
- name: mytestacc-token-z4jwk
