apiVersion: v1
kind: Service
metadata:
  name: frontback-svc
  labels:
    app: frontback
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: frontback
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
spec:
  serviceName: frontback
  replicas: 3
  selector:
    matchLabels:
      app: frontback
  template:
    metadata:
      labels:
        app: frontback
    spec:
      containers:
      - name: cassandra
        image: gcr.io/google-samples/cassandra:v13
        ports:
        - containerPort: 80
          name: bd
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
