apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "myapp.fullname" . }}
  labels:
    app:  {{ template "myapp.name" . }}
    tier: backend    
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{ template "myapp.name" . }}
      tier: backend 
  template:
    metadata:     
      labels:
        app:  {{ template "myapp.name" . }}
        tier: backend 
    spec:           
      containers:
      - env:
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_NAME
          value: product
        - name: DATABASE_PASSWORD
          value: pr0dr0b0t
        - name: DATABASE_USER
          value: product_robot
        - name: DATABASE_PORT
          value: "5432"
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        name: {{ .Values.backend.name }}
        ports:
        - containerPort: 8080
      restartPolicy: Always
