apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app:  {{ .Values.application }}
    tier: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      name: http
  selector:
    app:  {{ .Values.application }}
    tier: backend
