apiVersion: v1
kind: Service
metadata:
  name: {{ template "myapp.fullname" . }}
  labels:
    app: {{ template "myapp.name" . }}
    tier: postgres
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
  selector:
    app: {{ template "myapp.name" . }}
    tier: postgres
