replicaCount: 1

application: ecomm_test
name: prod-fe-test

image:
  repository: chrischinchilla/humanitech-product-fe
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 8080
