replicaCount: 1

application: ecomm_test
name: prod-be-test

image:
  repository: chrischinchilla/humanitech-product-be
  pullPolicy: IfNotPresent


service:
  type: NodePort
  port: 80
  targetPort: 8080
